export const HOST = "http://localhost:8000"

export const URL_USER_ALL = "/user/all"
export const URL_USER_LOGIN = "/user/login"
export const URL_USER_BLOCK = "/user/block"
export const URL_USER_UPDATE = "/user/update"
export const URL_USER_SELECTED = "/user/selected"
export const URL_USER_REGISTER = "/user/register"
export const URL_USER_FORGET = "/user/password/forget"

export const URL_ALL_FOOD = "/all/food"
export const URL_TODAY_FOOD = "/today/food"
export const URL_CREATE_FOOD = "/create/food"
export const URL_DELETE_FOOD = "/delete/food"
export const URL_UPDATE_FOOD = "/update/food"
export const URL_SELECTED_FOOD = "/selected/food"

export const URL_MESSAGE_ALL = "/all/messages"
export const URL_MESSAGE_USER = "/user/message"
export const URL_MESSAGE_CREATE = "/create/message"
export const URL_MESSAGE_DELETE = "/delete/message"
export const URL_MESSAGE_UPDATE = "/update/message"
export const URL_MESSAGE_SELECTED = "/selected/message"

export const URL_ORDER_ALL = "/all/orders"
export const URL_ORDER_USERID = "/user/order"
export const URL_ORDER_TODAY = "/today/orders"
export const URL_ORDER_CREATE = "/create/order"
export const URL_ORDER_DELETE = "/delete/order"
export const URL_ORDER_SELECTED = "/selected/order"